# Generated by Django 6.0.3 on 2026-04-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id_historico', models.AutoField(primary_key=True, serialize=False)),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('desc_historico', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'historico',
            },
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id_localizacao', models.AutoField(primary_key=True, serialize=False)),
                ('desc_localizacao', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'localizacao',
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id_ordem_servico', models.AutoField(primary_key=True, serialize=False)),
                ('prioridade_urgencia', models.CharField(choices=[('B', 'Baixa'), ('M', 'Média'), ('A', 'Alta')], max_length=1)),
                ('status_ordem_servico', models.CharField(choices=[('A', 'Aberta'), ('E', 'Em andamento'), ('C', 'Concluída'), ('F', 'Fechada')], max_length=1)),
                ('dt_abertura', models.DateField(auto_now_add=True)),
                ('dt_conclusao', models.DateField(blank=True, null=True)),
                ('descricao_servico', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'ordem_servico',
            },
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id_predio', models.AutoField(primary_key=True, serialize=False)),
                ('nome_predio', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'predio',
            },
        ),
    ]
