# Generated by Django 6.0.3 on 2026-04-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='especificacao_local',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='identificacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tipo_solicitante',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
