# Generated by Django 6.0.3 on 2026-04-05 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordemservico_especificacao_local_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='especificacao_local',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='identificacao',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='tipo_solicitante',
        ),
    ]
