# Generated by Django 6.0.3 on 2026-05-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id_localizacao', models.BigAutoField(primary_key=True, serialize=False)),
                ('desc_localizacao', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'localizacao',
                'managed': False,
            },
        ),
    ]
