# Generated by Django 6.0.3 on 2026-05-16 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('predio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id_localizacao', models.BigAutoField(primary_key=True, serialize=False)),
                ('desc_localizacao', models.CharField(max_length=150)),
                ('predio', models.ForeignKey(db_column='id_predio', on_delete=django.db.models.deletion.DO_NOTHING, to='predio.predio')),
            ],
            options={
                'db_table': 'localizacao',
                'managed': True,
            },
        ),
    ]
