# Generated by Django 6.0.3 on 2026-03-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id_solicitante', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSolicitante',
            fields=[
                ('id_tipo_solicitante', models.AutoField(primary_key=True, serialize=False)),
                ('desc_tipo_solicitante', models.CharField(max_length=150)),
            ],
        ),
    ]
