# Generated by Django 6.0.3 on 2026-03-29 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AprovarOrdemServico',
            fields=[
                ('id_aprovacao', models.AutoField(primary_key=True, serialize=False)),
                ('desc_aprovacao', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ClassificacaoPrioridade',
            fields=[
                ('id_classificacao_prioridade', models.AutoField(primary_key=True, serialize=False)),
                ('desc_classificacao_prioridade', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='GraficoIndicadores',
            fields=[
                ('id_grafico', models.AutoField(primary_key=True, serialize=False)),
                ('desc_grafico', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoAnterior',
            fields=[
                ('id_historico_anterior', models.AutoField(primary_key=True, serialize=False)),
                ('desc_historico', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id_localizacao', models.AutoField(primary_key=True, serialize=False)),
                ('desc_localizacao', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id_predio', models.AutoField(primary_key=True, serialize=False)),
                ('nome_predio', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Prioridade',
            fields=[
                ('id_prioridade', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RecusarOrdemServico',
            fields=[
                ('id_recusa', models.AutoField(primary_key=True, serialize=False)),
                ('desc_recusa', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='StatusOrdemServico',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('desc_status_ordem_servico', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='StatusValidacao',
            fields=[
                ('id_status_validacao', models.AutoField(primary_key=True, serialize=False)),
                ('desc_status_validacao', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAcaoOrdemServico',
            fields=[
                ('id_tipo_acao_ordem_servico', models.AutoField(primary_key=True, serialize=False)),
                ('desc_tipo_acao', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id_tipo_servico', models.AutoField(primary_key=True, serialize=False)),
                ('desc_tipo_servico', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TrocarOrdemServico',
            fields=[
                ('id_troca', models.AutoField(primary_key=True, serialize=False)),
                ('desc_troca', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Validacao',
            fields=[
                ('id_validacao', models.AutoField(primary_key=True, serialize=False)),
                ('desc_validacao', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id_historico', models.AutoField(primary_key=True, serialize=False)),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('descricao', models.CharField(max_length=150)),
                ('historico_anterior', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.historicoanterior')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id_ordem_servico', models.AutoField(primary_key=True, serialize=False)),
                ('dt_conclusao', models.DateField(blank=True, null=True)),
                ('dt_abertura', models.DateField(auto_now_add=True)),
                ('gestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestor.gestor')),
                ('localizacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.localizacao')),
            ],
        ),
    ]
