# Generated by Django 6.0.3 on 2026-03-29 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestor', '0001_initial'),
        ('orders', '0001_initial'),
        ('tecnico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='tecnico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tecnico.tecnico'),
        ),
        migrations.AddField(
            model_name='historico',
            name='ordem_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ordemservico'),
        ),
        migrations.AddField(
            model_name='graficoindicadores',
            name='ordem_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ordemservico'),
        ),
        migrations.AddField(
            model_name='localizacao',
            name='predio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.predio'),
        ),
        migrations.AddField(
            model_name='prioridade',
            name='classificacao_prioridade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.classificacaoprioridade'),
        ),
        migrations.AddField(
            model_name='prioridade',
            name='gestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestor.gestor'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='prioridade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.prioridade'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.statusordemservico'),
        ),
        migrations.AddField(
            model_name='tipoacaoordemservico',
            name='aprovacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.aprovarordemservico'),
        ),
        migrations.AddField(
            model_name='tipoacaoordemservico',
            name='gestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestor.gestor'),
        ),
        migrations.AddField(
            model_name='tipoacaoordemservico',
            name='recusa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.recusarordemservico'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tipo_servico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.tiposervico'),
        ),
        migrations.AddField(
            model_name='tipoacaoordemservico',
            name='troca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.trocarordemservico'),
        ),
        migrations.AddField(
            model_name='validacao',
            name='status_validacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.statusvalidacao'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='validacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.validacao'),
        ),
    ]
