# Generated by Django 6.0.3 on 2026-05-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id_ordem_servico', models.BigAutoField(primary_key=True, serialize=False)),
                ('prioridade_urgencia', models.CharField(max_length=20)),
                ('status_ordem_servico', models.CharField(max_length=30)),
                ('dt_abertura', models.DateTimeField()),
                ('dt_conclusao', models.DateTimeField(blank=True, null=True)),
                ('descricao_servico', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ordem_servico',
                'managed': False,
            },
        ),
    ]
