# Generated by Django 6.0.3 on 2026-05-16 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localizacao', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id_ordem_servico', models.BigAutoField(primary_key=True, serialize=False)),
                ('prioridade_urgencia', models.CharField(max_length=20)),
                ('status_ordem_servico', models.CharField(max_length=30)),
                ('dt_abertura', models.DateTimeField()),
                ('dt_conclusao', models.DateTimeField(blank=True, null=True)),
                ('descricao_servico', models.CharField(max_length=255)),
                ('gestor', models.ForeignKey(blank=True, db_column='id_gestor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordens_gerenciadas', to='usuario.usuario')),
                ('localizacao', models.ForeignKey(db_column='id_localizacao', on_delete=django.db.models.deletion.DO_NOTHING, to='localizacao.localizacao')),
                ('solicitante', models.ForeignKey(db_column='id_solicitante', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordens_abertas', to='usuario.usuario')),
                ('tecnico', models.ForeignKey(blank=True, db_column='id_tecnico', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordens_atribuidas', to='usuario.usuario')),
            ],
            options={
                'db_table': 'ordem_servico',
                'managed': True,
            },
        ),
    ]
