# Generated by Django 6.0.3 on 2026-05-17 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativo', '0002_remove_ativo_data_instalacao'),
        ('ordem_servico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='ativo',
            field=models.ForeignKey(blank=True, db_column='id_ativo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ativo.ativo'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tipo_manutencao',
            field=models.CharField(default='GERAIS', max_length=30),
        ),
    ]
