# Generated by Django 6.0.3 on 2026-05-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_servico', '0002_ordemservico_ativo_ordemservico_tipo_manutencao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='categoria_manutencao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='tipo_manutencao',
            field=models.CharField(default='CORRETIVA', max_length=30),
        ),
    ]
