# Generated by Django 6.0.3 on 2026-05-27 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_servico', '0003_ordemservico_categoria_manutencao_and_more'),
        ('usuario', '0002_usuario_dt_expiracao_token_usuario_email_confirmado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='solicitante',
            field=models.ForeignKey(blank=True, db_column='id_solicitante', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordens_abertas', to='usuario.usuario'),
        ),
    ]
