# Generated by Django 6.0.3 on 2026-05-16 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localizacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id_ativo', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_patrimonial', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_ativo', models.CharField(choices=[('AR_CONDICIONADO', 'Ar Condicionado'), ('BEBEDOURO', 'Bebedouro')], max_length=30)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serial', models.CharField(blank=True, max_length=100, null=True)),
                ('data_instalacao', models.DateField(blank=True, null=True)),
                ('periodicidade_preventiva_dias', models.IntegerField(default=90)),
                ('dt_ultima_preventiva', models.DateField(blank=True, null=True)),
                ('dt_proxima_preventiva', models.DateField(blank=True, null=True)),
                ('localizacao', models.ForeignKey(db_column='id_localizacao', on_delete=django.db.models.deletion.DO_NOTHING, to='localizacao.localizacao')),
            ],
            options={
                'db_table': 'ativo',
                'managed': True,
            },
        ),
    ]
