# Generated by Django 6.0.3 on 2026-05-16 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ativo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ativo',
            name='data_instalacao',
        ),
    ]
