# Generated by Django 6.0.3 on 2026-03-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id_gerente', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
