# Generated by Django 6.0.3 on 2026-03-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id_gestor', models.AutoField(primary_key=True, serialize=False)),
                ('area_atuacao', models.CharField(max_length=150)),
            ],
        ),
    ]
