# Generated by Django 6.0.3 on 2026-05-26 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupo_usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupousuario',
            options={'managed': False},
        ),
    ]
