# Generated by Django 6.0.3 on 2026-05-27 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupo_usuario', '0002_alter_grupousuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupousuario',
            options={'managed': True},
        ),
    ]
