# Generated by Django 6.0.3 on 2026-05-16 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordem_servico', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id_historico_ordem_servico', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_registro', models.DateTimeField()),
                ('desc_historico', models.CharField(max_length=255)),
                ('ordem_servico', models.ForeignKey(db_column='id_ordem_servico', on_delete=django.db.models.deletion.CASCADE, to='ordem_servico.ordemservico')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.usuario')),
            ],
            options={
                'db_table': 'historico',
                'managed': True,
            },
        ),
    ]
