# Generated by Django 6.0.3 on 2026-05-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id_historico_ordem_servico', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_registro', models.DateTimeField()),
                ('desc_historico', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'historico',
                'managed': False,
            },
        ),
    ]
